version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx_node
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app_node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    command: node index.js

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - 3306:3306


networks:
  node-network:
    driver: bridge
